<?php

namespace AppBundle\Repository;

/**
 * replyreclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class replyreclamationRepository extends \Doctrine\ORM\EntityRepository
{
}
