<?php

namespace MyApp\JobOwnerBundle\Repository;

/**
 * ChoixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoixRepository extends \Doctrine\ORM\EntityRepository
{
}
