<?php

namespace MyApp\JobOwnerBundle\Repository;

/**
 * TestresultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestresultsRepository extends \Doctrine\ORM\EntityRepository
{
}
