<?php

namespace MyApp\FreelancerBundle\Repository;

/**
 * TrainingSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
